version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    depends_on:
      - mongo
    env_file:
      - ./.env
    container_name: web
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
  nginx:
    depends_on:
      - web
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    container_name: nginx